### ISSUE TITLE
Stop text animation with single variable after one loop

### ISSUE THREAD

**Issue by motorambler** [getgrav/grav-plugin-shortcode-ui#10]
Is it possible to stop the animation after **one loop** when using only **one variable** for the animated text? Using the below example, the loading bar never stops going back and forth under the word "Contact", and quickly becomes distracting.

[ui-animated-text words="Contact" animation="loading-bar" element="h3"][/ui-animated-text]

**Comment by rhukster** [comment]
That's beyond the simple CSS animation this plugin uses.  You might want to look at typed.js - http://www.mattboldt.com/demos/typed-js/
