### ISSUE TITLE
Markdown in tabs being escaped instead of rendered

### ISSUE THREAD

**Issue by aloysius-lim** [getgrav/grav-plugin-shortcode-ui#11]
Markdown within tabs are escaped, so the browser shows the html code instead of rendering it to display the content.

To reproduce, add this to any Grav page:

    [ui-tabs]

    [ui-tab title="Bash (curl)"]
    ```bash
    # Bash code here
    ```
    [/ui-tab]

    [ui-tab title="Python"]
    ```python
    # Python code here
    ```
    [/ui-tab]

    [/ui-tabs]

This should render the Markdown output in each tab, for example:

```bash
# Bash code here
```

```python
# Python code here
```

Instead, I get raw html shown in the tabs:

`<pre><code class="language-bash"># Bash code here</code></pre>`

and

`<pre><code class="language-python"># Python code here</code></pre>`

**Comment by rhukster** [comment]
Please try latest release should output raw now.
