### ISSUE TITLE
Animated text is slightly cut off

### ISSUE THREAD

**Issue by Endogen** [getgrav/grav-plugin-shortcode-ui#13]
I use this shortcode `[ui-animated-text words="CRACKCAT.DE" animation="slide" element="h1"]WTF ist [/ui-animated-text]`. When i navigate to the page, everything is fine but if i reload the page, the `E` gets cut off. This is in Safari.

![safari_cut_off](https://cloud.githubusercontent.com/assets/226475/22400575/237c7158-e5b9-11e6-9bbe-019692ca3a32.png)

In Chrome, if i reload the page, everything is fine but when i copy the URL and enter it in a new tab, it also is slightly cut off

![chrome_cut_off](https://cloud.githubusercontent.com/assets/226475/22400581/51f00bf8-e5b9-11e6-8e3b-e1dfe1b20ffe.png)

macOS 10.11.6 - grav 1.1.14 - Safari 10.0.3 - Chrome 55.0.2883

**Comment by rhukster** [comment]
Pretty sure this is related to the font more than anything. Try another font?

**Comment by Endogen** [comment]
I didn't try another font yet but shouldn't this work with the default font?

**Comment by rhukster** [comment]
I didn't write the script that does this animation, so this is really beyond anything I can fix.  Try another font, if that doesn't work, then maybe look at typed.js. I only added this because i needed it for a project and thought others would enjoy it also.

**Comment by Endogen** [comment]
Thanks for the information. Glad you added it! I will use it anyway and try to change the font.
