### ISSUE TITLE
Assets not loaded on modular pages

### ISSUE THREAD

**Issue by cord** [getgrav/grav-plugin-shortcode-ui#14]
Hi andy,

latest grav and plugin version:

on a modular page the assets (js+css) are not added when a subpage utilizes a shortcode. The shortcode itself is processed (html structure created)

workaround:

insert a shortcode in html comments
``

at the and of the modular.md

so looks like the the ->addAssets() calls are fired too late?

/cord

**Comment by sunyatasattva** [comment]
A workaround would be to use the `addCSS` API, like so:

`
$this->grav['assets']->addCss('plugin://shortcode-ui/css/ui-tooltips.css');`

**Comment by cord** [comment]
@rhukster any solution for this situation?

**Comment by rhukster** [comment]
I found a bug with modular assets being added correctly but not being found and subsequently they were not being retrieved and actually added to the asset manager.  This was fixed in the last release. 

I know this is fixed because I am using this vey feature in a project.

**Comment by rhukster** [comment]
https://github.com/getgrav/grav-plugin-shortcode-core/blob/develop/CHANGELOG.md

**Comment by cord** [comment]
I can confirm the issue is fixed after updating, thanks a lot!
