### ISSUE TITLE
Accordion shortcode ?

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-shortcode-ui#15]
An accordion shortcode would be a nice feature/enhancement...?

**Comment by rhukster** [comment]
Just added!!!

**Comment by axel-rank** [comment]
Great! Thank you. Is this accordian aria accessible? Or can I add it manually?

**Comment by rhukster** [comment]
two options, submit a PR on the current shortcode's twig to add that, or just copy it to your theme, and edit it.
