### ISSUE TITLE
Update breaks site

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav-plugin-shortcode-ui#18]
Newest update to 2.2.1 breaks site and admin:
![error](https://cloud.githubusercontent.com/assets/12480617/23563884/f128c0bc-0048-11e7-88cd-febe7be43bcf.png)

Guess it's because gravstrap plugin which uses accordion shortcode/name too?
Think accordian was better name

**Comment by rhukster** [comment]
Hmm. I can't replicate this.. try uninstalling and reinstalling shortcode-ui plugin.

**Comment by rhukster** [comment]
oh!.. missed your thing about gravstrap.. yes probably does conflict

**Comment by axel-rank** [comment]
Yes it does, uninstall of Gravstrap solved the issue.
Seems that I (and other users) have to choose between them?
Not too happy about that, because gravstrap has a lot of good shortcodes and modules I don't wanna miss.
So for now I uninstalled shortcode-ui...

**Comment by rhukster** [comment]
I'll change the classname.. not happy though.. I like things to be consistent! :)
