### ISSUE TITLE
ui-accordion open=0 gets an argument error

### ISSUE THREAD

**Issue by blueforce** [getgrav/grav-plugin-shortcode-ui#29]
Steps to reproduce:
1. User Shortcode Accordeon
2. Set [ui-accordion independent=false open=0]
3. see result

Failure:
Server Error
Sorry, something went terribly wrong!

0 - Argument 1 passed to Grav\Plugin\ShortcodeManager::getId() must implement interface Thunder\Shortcode\Shortcode\ShortcodeInterface, null given, called in root/user/plugins/shortcode-ui/shortcodes/AccordionsShortcode.php on line 33

Tested with:
- UI Shortcode v2.2.5
- PHP 7.2.x
- Grav v1.5.6 
- Admin v1.8.15

**Comment by rhukster** [comment]
Well i've looked into this and it appears to be a bug in the upstream shortcode library.  Basically, the `open=0` is causing the top parent of the child item to be null.  If you use: `open="0"` it works fine.

It seems to be a problem specifically with the `regular` parser, as `wordpress` and `regex` work fine.

**Comment by blueforce** [comment]
no code added? is there a workarround?

**Comment by rhukster** [comment]
The fix was 'downstream' in the `thunderer/shortcode` library we use:

https://github.com/getgrav/grav-plugin-shortcode-core/commit/f1359f3ff1cd890580f8c94ce31df494a3e63670

**Comment by rhukster** [comment]
also i put workarounds while we were waiting for the updated release of the library here: https://github.com/getgrav/grav-plugin-shortcode-ui/issues/29#issuecomment-459602692

**Comment by blueforce** [comment]
thanks a lot, much appricieated

**Comment by iamalive-now** [comment]
Hi
I've just started a new site and have added the shortcode ui plugin.
I'm getting much the same error as described above:

"Argument 1 passed to Grav\Plugin\ShortcodeCore\ShortcodeManager::getId() must implement interface Thunder\Shortcode\Shortcode\ShortcodeInterface, null given, called in /home/iamalive/mysite.com/user/plugins/shortcode-ui/classes/shortcodes/AccordionsShortcode.php on line 34 ◀"

I'm using Gantry5 and the Helium Template.

Any ideas?

**Comment by rhukster** [comment]
Are you in the latest version of shortcode core??

**Comment by iamalive-now** [comment]
Hi Andy

I installed via Admin panel - the whole site is only a few days old so I
assume it includes all the new plugins, etc.

Regards
David

David Jakob
Längmattstrasse 31
CH-4632 Trimbach
Switzerland
Tel.:+41 62 535 4394

**Comment by rhukster** [comment]
Can you paste your md content?

**Comment by iamalive-now** [comment]
Hi Andy

I probably could, but not sure where to look and exactly which md file you
mean.

I'm happy to give you full access:
[EDIT: credentials have been moved out -Matias]

Hope that helps.

Regards
David

David Jakob
Längmattstrasse 31
CH-4632 Trimbach
Switzerland
Tel.:+41 62 535 4394

**Comment by iamalive-now** [comment]
Hi again Andy

Just to follow up: on my site I have a page called "Terms & Conditions"
where I have experimented with the accordion shortcode. This is where the
error message can be seen on the frontend.

Incidentally, I'd like to take the opportunity to thank you for your many
achievements, which have directly contributed to me being able to earn a
living for the past 17 years, starting with Joomla Version and Rockettheme
practically from the beginning. I am very impressed by you and your teams.

Regards
David

David Jakob
Längmattstrasse 31
CH-4632 Trimbach
Switzerland
Tel.:+41 62 535 4394

**Comment by mahagr** [comment]
@iamalive-now Please do not send any login credentials into a public discussion (you replied to GitHub notification). I removed them from the GitHub discussion.

**Comment by iamalive-now** [comment]
Follow up:

I have found the error - I had not added the closing tag for the accordion!
My bad! My apologies.

Best regards
David

David Jakob
Längmattstrasse 31
CH-4632 Trimbach
Switzerland
Tel.:+41 62 535 4394

**Comment by iamalive-now** [comment]
Hi Matias

Ooops! Sorry - I didn't realise it would get publicly published. Thanks for
removing that!!! I've deleted that account already.

Best regards
David

David Jakob
Längmattstrasse 31
CH-4632 Trimbach
Switzerland
Tel.:+41 62 535 4394
