### ISSUE TITLE
nested accordion items

### ISSUE THREAD

**Issue by fugo** [getgrav/grav-plugin-shortcode-ui#40]
I tried something like this (in a modular page) but the nested accordions don’t show up. Also I tried `ui-tabs` with the same afford.
Is it not possible to have nested accordions/tabs?

```
[ui-accordion independent=true open=none]
[ui-accordion-item title="SOMETHING 1"]
some stuff
[/ui-accordion-item]
[ui-accordion-item title="SOMETHING 2"]
    [ui-accordion]
    [ui-accordion-item title="SOMETHING nested 1"]
          more stuff
    [/ui-accordion-item]
    [ui-accordion-item title="SOMETHING nested 2"]
           stuff…
    [/ui-accordion-item]
    [ui-accordion]
[/ui-accordion-item]
[/ui-accordion]
```

TIA

**Comment by rhukster** [comment]
For full nested support, make sure you have the 'regular' parser enabled in `shortcode-core`:

```yaml
parser: regular
```

**Comment by fugo** [comment]
Thanks will look for this. → Processor: RegularParser in Admin shortcode-core plugin
I saw with tabs I got empty divs


```
  | <div class="tabs-wrapper ui-theme-default top-left">
  | <ul class="tabs-nav">
  | </ul>
  | <div class="tabs">
  | </div>
  | </div>
  |  
  | </article>
  | </div>
```

**Comment by fugo** [comment]
After i put the tabs outside the accordion, page was chrashing `Crickey` about ID shortcode core line ~328 (something about ID)
Put it bBack again and it works also the accordion inside :smile: 
Don’t know what happend. I allways delete **all caches**
Nevermind it’s working. Thank you a lot for this fine shortcode. :+1:
