### ISSUE TITLE
Possible to center tabs?

### ISSUE THREAD

**Issue by Endogen** [getgrav/grav-plugin-shortcode-ui#7]
Is it possible to center the tabs? Something like `[ui-tabs position="centered" active="0" theme="lite"]`would be nice

**Comment by cord** [comment]
you can center the tabs with some CSS:
```
.tabs-nav {
    text-align: center;
}
```

**Comment by Endogen** [comment]
Thanks for the answer but i already tried to set that. Only file with that content is `/user/plugins/shortcode-ui/scss/ui-tabs.scss` and i tried to replace / insert it everywhere i could find `.tabs-nav {` but that didn't help. Sorry for the stupidity but i don't get how the whole thing works... Any chance you could explain it a bit deeper?

**Comment by rhukster** [comment]
really you should but more specific CSS in your theme's CSS, don't put things in the `ui-tabs.css` as that will be overwritten with plugin updates...

```
body .tabs-nav {
    text-align: center;
}
```
